name: CI Rust
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  ci:
    name: CI Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Test
        run: |
          cargo test

      - name: Coverage Check
        run: |
          cargo llvm-cov

      - name: Linting
        run: |
          cargo clippy -- -D warnings

      - name: Formatting
        run: |
          cargo fmt --check

      - name: Security audit
        run: |
          cargo audit